# -*- coding: utf-8 -*-
"""00_pytorch_fundamentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rs4YIRzCVRGhkuTZBlncSTnsQ-JYRCdy

## 00. PyTorch Fundamentals.
"""

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

!nvidia-smi

"""##Creating tensor

"""

#scalar
scalar = torch.tensor(7)
scalar

#get tensor back as python int
scalar.item()

vector = torch.tensor([7,7])
vector

vector.ndim

vector.shape

#MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

MATRIX.ndim

MATRIX[0]

MATRIX[1]

MATRIX.shape

#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

TENSOR.ndim

